version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7-apache
    container_name: php-docker
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - mon-reseau
   
  db:
    image: mysql:8.0
    container_name: mysql-docker
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    networks:
      - mon-reseau

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-docker
    environment:
      PMA_HOST: db
      PMA_PORT: 3307
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - mon-reseau

networks:
  mon-reseau:





# version: '3'

# services:
#   mysql:
#     image: mysql:8.2.0
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: laravel
#     networks:
#       - count-money_default

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:80"
#     # restart: always  
#     depends_on:
#       - mysql
#     restart: always   
#     command: ["bash", "-c", "service mysql start && mysql -u root -e \"CREATE DATABASE laravel;\" && php artisan migrate","php artisan serve"]  
#     # command: ["bash", "-c", "php artisan migrate --force"]
#     networks:
#       - count-money_default

# networks:
#   count-money_default:
#     external: true




# version: '3'

# services:
#   mysql:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: laravel

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:80"
#     depends_on:
#       - mysql
#     command: ["bash", "-c", "sleep 30 && php artisan migrate --force"]








# version: '3'

# services:
#   mysql:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_DATABASE: laravel
#     networks:
#       - back  
   

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:80"
#     networks:
#       - front 
#     depends_on:
#       - mysql

# networks:
#   back:
#   front:
# volumes:
#   front:

